### ISSUE TITLE
Suggestion: Include a mini sample project that shows use of component, CSS, Tokens

### ISSUE THREAD

**Issue by jdittrich** [wmde/wikit#205]
**Story:** I want to start using Wikit quickly. The documentation is all there, but I do not know how to use it in an actual project. 

**Possible solution:** Provide a small, bare-bones example 'app' with the repo and/or documentation which shows: 

- A simple UI made of a few components
- Use of design tokens (or should 'users' of the components never need to use them?)

**Comment by SaiSan-WMDE** [comment]
Hello Jan! I'm very grateful for your suggestion! I'll be moving it to the [design system's Phab board](https://phabricator.wikimedia.org/project/board/4521/).

I interpret that you're encouraging us to create a sample app that allows users to see components in action and to "visualize" the tokens shaping them. Were you picturing the tokens being displayed in a particular way? What would be more suitable? 

As a heads-up, achieving to display component-level tokens in Storybook (at component/ story level) is something that's still open for exploration ([T260425](https://phabricator.wikimedia.org/T260425)). Right now, the only way to see how tokens are applied is by checking [component specs in Figma](https://www.figma.com/file/gi3JYwSUQYhKS0mHwK25cQwi/?node-id=2967%3A8), or of course the [components' tokens json files](https://github.com/wmde/wikit/tree/master/tokens/properties/components).

Regarding your question: users of existing components might never have to use/modify tokens. They become contributors in case a visual spec needs to be updated, or a variant of a system component needs to be implemented. Seeing design tokens in context may be useful in this case.

**Comment by wiese** [comment]
(Could not find the respective ticket on the phab board, so responding here - maybe we should disable "issues" here and link people to phab right away)

Responding merely as someone who took part in the initial hike and, of course, had some ideas of how things would proceed...



> * A simple UI made of a few components

I'm interpreting "how to use it in an actual project" as a best practice kind of place to copy from.
It always was assumption that the "Show code" link as seen e.g. on https://wmde.github.io/wikit/?path=/docs/vue_icon--all would serve this purpose. Combined with https://wmde.github.io/wikit/?path=/docs/documentation-getting-started--page#1-install-via-npm this should get a developer started.

The "Show code" links IMO unfortunately had a lot of their clarity removed when multiple stories were grouped into one (#160).

> * Use of design tokens (or should 'users' of the components never need to use them?)

I assume that many/most applications will not exclusively be built from ready-made wikit components but will need some additional ones (maybe to be upstreamed at some point in the future) or add some skeleton around them which should have a similar flavor no less - so I assume that most applications will have a need for tokens on top of components (even when wikit is in a much more "complete" state than now). How to get to them is documented here: https://wmde.github.io/wikit/?path=/docs/documentation-getting-started--page#using-tokens

Pointers how we could make this more approachable are very welcome.

**Comment by SaiSan-WMDE** [comment]
Here's the ticket: https://phabricator.wikimedia.org/T264733

(Was added to the backlog respecting the current priority)

**Comment by wiese** [comment]
Created #206 for the "only use phab as an issue tracker" discussion.

**Comment by Ladsgroup** [comment]
Closing in favor of the pharbicator ticket.
